volumes:
  pg_data:

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: tr-app
    depends_on:
      - db
    ports:
      - 8000:8000
